### ISSUE TITLE
omnirom 6.0.1 build error!

### ISSUE THREAD

**Issue by blue59** [omnirom/android_kernel_samsung_aries#3]
what should i do for fix it? my rom build complete but i have this error 
`Kernel: arch/arm/boot/zImage is ready
make[1]: Leaving directory`/home/ibrahim/wave/kernel/samsung/aries'
make  -C kernel/samsung/aries O=/home/ibrahim/wave/out/target/product/wave/obj/KERNEL_OBJ ARCH=arm CROSS_COMPILE=" "/home/ibrahim/wave/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/"/arm-eabi-" dtbs
make[1]: Entering directory `/home/ibrahim/wave/kernel/samsung/aries'
make[2]: *** No rule to make target`dtbs'.  Stop.
make[1]: **\* [sub-make] Error 2
make[1]: Leaving directory `/home/ibrahim/wave/kernel/samsung/aries'
make: [TARGET_KERNEL_BINARIES] Error 2 (ignored)
make  -C kernel/samsung/aries O=/home/ibrahim/wave/out/target/product/wave/obj/KERNEL_OBJ ARCH=arm CROSS_COMPILE=" "/home/ibrahim/wave/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/"/arm-eabi-" modules
make[1]: Entering directory`/home/ibrahim/wave/kernel/samsung/aries'
  GEN     /home/ibrahim/wave/out/target/product/wave/obj/KERNEL_OBJ/Makefile
  CHK     include/linux/version.h
`

**Comment by maxwen** [comment]
this is not the place for such questions. use IRC #omni
